version: '3'

services:
  turbosort:
    build: .
    container_name: turbosort
    volumes:
      - ${SOURCE_VOLUME}:/app/source # Source directory (used if USE_S3_SOURCE=false)
      - ${DESTINATION_VOLUME}:/app/destination # Destination directory
      - ${HISTORY_VOLUME}:/app/history # Directory to store history file
    env_file:
      - .env
    environment:
      - USE_S3_SOURCE=${USE_S3_SOURCE:-false}
      - S3_ENDPOINT=${S3_ENDPOINT:-http://minio:9000}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY:-minioadmin}
      - S3_SECRET_KEY=${S3_SECRET_KEY:-minioadmin}
      - S3_BUCKET=${S3_BUCKET:-turbosort-source}
      - S3_REGION=${S3_REGION:-us-east-1}
      - S3_PATH_PREFIX=${S3_PATH_PREFIX:-}
    restart: unless-stopped 