version: '3'

services:
  turbosort:
    build: .
    container_name: turbosort
    volumes:
      - ${SOURCE_VOLUME}:/app/source # Source directory
      - ${DESTINATION_VOLUME}:/app/destination # Destination directory
      - ${HISTORY_VOLUME}:/app/history # Directory to store history file
    env_file:
      - .env
    restart: unless-stopped 